# ===========================
# Global Configuration
# ===========================
global:
  scrape_interval: 15s

# ===========================
# Alertmanager Configuration
# ===========================
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'  # Alertmanager host

# ===========================
# Alert Rules
# ===========================
rule_files:
  - "/etc/prometheus/rules/*.yml"

# ===========================
# Scrape Configurations
# ===========================

scrape_configs:

  # ===========================
  # DC1: Triple-Play
  # ===========================

  # --- Node Exporter ---
  - job_name: 'node_exporter_Triple-Play'
    scrape_interval: 1s
    static_configs:
      - targets:
          - '150.242xxc:9100'
        labels:
          dc: 'Triple-Play'
          service: 'node'

  # --- MySQL Exporter ---
  - job_name: 'mysql_exporter_Triple-Play'
    scrape_interval: 25s
    scrape_timeout: 15s  
    static_configs:
      - targets:
          - '150.2xx50:9104'
        labels:
          dc: 'Triple-Play'
          service: 'mysql'

  # --- Asterisk Exporter ---
  - job_name: 'asterisk_exporter_Triple-Play'
    scrape_interval: 15s
    static_configs:
      - targets:
          - '150xx9700'
        labels:
          dc: 'Triple-Play'
          service: 'asterisk'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

     # --- PM2 Exporter ---
     #  - job_name: 'pm2_exporter_Triple-Play'
     #scrape_interval: 15s
     #static_configs:
     #  - targets:
     #     - '150xx9209'
     #   labels:
     #     dc: 'Triple-Play'
     #     service: 'pm2'
     # relabel_configs:
     # - source_labels: [__address__]
     #   target_label: instance
       

  # ===========================
  # DC2: V-Connect
  # ===========================

  # --- Node Exporter ---
  - job_name: 'node_exporter_V-Connect'
    scrape_interval: 15s
    static_configs:
      - targets:
          - '16xxx100'

        labels:
          dc: 'V-Connect'
          service: 'node'


  # ===========================
  # DC4: Office-Servers
  # ===========================

  # --- Node Exporter ---
  - job_name: 'node_exporter_Office'
    scrape_interval: 15s
    static_configs:
      - targets:
          - '192.1xx100'
 
        labels:
          dc: 'Office-Servers'
          service: 'node'
 

  # --- MySQL Exporter ---
  - job_name: 'mysql_exporter_V-Connect'
    scrape_interval: 15s
    static_configs:
      - targets:
          - '163.xx4:9104'

        labels:
          dc: 'V-Connect'
          service: 'mysql'

  # --- Asterisk Exporter ---
  - job_name: 'asterisk_exporter_V-Connect'
    scrape_interval: 60s
    static_configs:
      - targets:
          - '163.2xx:9700'
        labels:
          dc: 'V-Connect'
          service: 'asterisk'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # ===========================
  # DC3: Microhost
  # ===========================

  # --- Node Exporter ---
  - job_name: 'node_exporter_Microhost'
    scrape_interval: 15s
    static_configs:
      - targets:
          - '10xx9:9100'
          - '150.24xx1:9100'
          - '150.xx100'
        labels:
          dc: 'Microhost'
          service: 'node'

  # --- MySQL Exporter ---
  - job_name: 'mysql_exporter_Microhost'
    scrape_interval: 15s
    static_configs:
      - targets:
          - '103xx'
          - '150.241xx04'  
        labels:
          dc: 'Microhost'
          service: 'mysql'

  # --- Asterisk Exporter ---
  - job_name: 'asterisk_exporter_Microhost'
    scrape_interval: 60s
    scrape_timeout: 50s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          - '103xx149:9700'
        labels:
          dc: 'Microhost'
          service: 'asterisk'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
          
